### ISSUE TITLE
Error if now exists output folder

### ISSUE THREAD

**Issue by abtris** [smizell/onit#2]
```
$ onit new

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/username/onit/days/2015-06-24.md'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at Command.newDay (/Users/abtris/.nvm/v0.10.37/lib/node_modules/onit/onit.js:174:8)
    at Command.listener (/Users/abtris/.nvm/v0.10.37/lib/node_modules/onit/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:98:17)
    at Command.parseArgs (/Users/abtris/.nvm/v0.10.37/lib/node_modules/onit/node_modules/commander/index.js:610:12)
    at Command.parse (/Users/abtris/.nvm/v0.10.37/lib/node_modules/onit/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/Users/abtris/.nvm/v0.10.37/lib/node_modules/onit/onit.js:99:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by abtris** [comment]
You can fix by `onit init` but this error is ugly.
